# training options
sampling_rate: 16000
frame_size: 400
frame_shift: 160
model_type: Transformer
max_epochs: 100
gradclip: 5
batchsize: 16
hidden_size: 256
num_frames: 500
num_speakers: 2
input_transform: logmel
optimizer: noam
lr: 1.0
context_size: 7
subsampling: 10
gradient_accumulation_steps: 1
transformer_encoder_n_heads: 4
transformer_encoder_n_layers: 4
transformer_encoder_dropout: 0.1
noam_warmup_steps: 25000
seed: 777
gpu: 1
