audio:
  n_fft: 512  # 8KHz setting : 512
  num_freq: 257   # n_fft/2+1, 8KHz setting : 257
  sample_rate: 16000
  hop_length: 256   # 8KHz setting : 256
  win_length: 512  # 8KHz setting : 512
  min_level_db: -100.0
  ref_level_db: 20.0
  preemphasis: 0.97
  power: 0.30

---
data:
  target_dir: '~~/TIMIT16K/origin/TIMIT16K/clean/'
  mixed_dir: '~~/TIMIT16K/origin/TIMIT16K/'
  train_ctrl_dir: '../ctrl/timit_train_full_path.fileids'
  test_ctrl_dir: '../ctrl/timit_valid_full_path_serve.fileids'
  
---
form:
  target:
    wav: '.wav'
  mixed:
    wav: '.wav'

---
train:
  batch_size: 16
  num_workers: 24
  max_audio_len: 124621
  optimizer: 'adam'
  adam: 0.001
  summary_interval: 1
  checkpoint_interval: 1000

---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
